### ISSUE TITLE
Select AutoUnbunch with no Vehicles Causes crash

### ISSUE THREAD

**Issue by Gregory365** [Gregory365/TPF2-Timetables#35]
- Create a line but don't add any vehicles to it
- Set a station on the line to AutoUnbunch
- Game crashes

**Comment by Gordon-Dry** [comment]
I read this but for some reason I managed to forget about it and accidentally did exactly this.
So I can confirm... *facepalm*

**Comment by pull2play** [comment]
Any possible fix for this? I know this isn't a massive issue, but in the heat of the moment I keep forgetting myself :)

**Comment by Gregory365** [comment]
@pull2play It has been fixed and pushed to steam workshop - Timetables 1.3
