### ISSUE TITLE
Crashes on 35320

### ISSUE THREAD

**Issue by naubasynema** [Gregory365/TPF2-Timetables#39]
Random crashes when playing the game, even when not have opened timetables during the session. Screenshot of latest crash included. The game has about 10 train lines with timetables. Crash occurred during ride along on a train that was not timetabled. Looks like not only TF2 crashed, but also the Steam launcher as that restarted.
I like this mod a lot, but at the moment it's very unstable for me. I'll try to help out what I can, but I'm not very familiar with lua scripting.

![image](https://github.com/Gregory365/TPF2-Timetables/assets/137615105/c0f5405b-ffb4-4a54-a680-f96565d7a9ca)

At the moment of the crash 33 other mods were active, most of them small stuff (train and truck stations, a few wagons, ...)

**Comment by Gregory365** [comment]
Thanks for reporting but I can't do anything with this error message.
The details and error message are blank (not your fault).
