### ISSUE TITLE
Release as Timetables 2?

### ISSUE THREAD

**Issue by wusatosi** [Gregory365/TPF2-Timetables#5]
Hi, I am thinking of using the time table mod, but seeing the original project is no longer being maintained and you have made meaningful changes to the mod and have kept working on this.
I wonder if you have any plan to publish your work on steam workshop as Timetables2?

Edit: Ops, just read your README, let me know if there's anything I can help!

**Comment by Gregory365** [comment]
Yes, this is planned as a steam workshop release once it is stable and reliable (doesn't crash)

Anyone can help by testing the mod and reporting any bugs or suggesting features.
