### ISSUE TITLE
Message "Timetables failed to resume dead coroutine." at start

### ISSUE THREAD

**Issue by wernk1** [Gregory365/TPF2-Timetables#55]
If I start a game, the message "Timetables failed to resume dead coroutine." appears permanently in the console/stdout. The mod does not work any longer. This issue has not been there before!

There is also an error displayed in the stdout:

"Timetables coroutine error: C:/Program Files (x86)/Steam/steamapps/workshop/content/1066780/2918585390/res/scripts/celmi/timetables/timetable.lua:632: attempt to compare number with nil"

**Comment by Gregory365** [comment]
Thank you for the report. I can see what is causing this. There will be a hotfix shortly
