### ISSUE TITLE
New beta - using scrollbar causes CTD

### ISSUE THREAD

**Issue by pull2play** [Gregory365/TPF2-Timetables#6]
I'm sure you're aware there was a new beta released a couple of days ago. FYI - opening the Timetable window in-game causes an immediate CTD. I'm not sure which one of your builds I'd been using prior to upgrading to the latest code, but it worked with the beta. I tried a rollback btw, but now it just keeps crashing outright, even if I use the old build.

Here's the pertinent blurb:

__CRASHDB_CRASH__ struct lua::LuaException: C:\GitLab-Runner\builds\1BJoMpBZ\0\ug\urban_games\train_fever\src\Game/scripting/error_handling.h:14: void __cdecl scripting::CheckResult<void>(struct sol::protected_function_result): [string "res/config/game_script/timetable_gui.lua"]:600: stack index 4, expected string, received sol.UI::ScrollArea*
Exception type: Lua exception

This error is usually caused by modding. Some game resources contain incorrect data.

Details:

Error message: [string "res/config/game_script/timetable_gui.lua"]:600: stack index 4, expected string, received sol.UI::ScrollArea*

Minidump: C:/Program Files (x86)/Steam/userdata/10038212/1066780/local/crash_dump/88e80586-92e2-4a5d-af60-6dfa8c6c67f7.dmp

In file: C:\GitLab-Runner\builds\1BJoMpBZ\0\ug\urban_games\train_fever\src\Game/scripting/error_handling.h:14

In function: void __cdecl scripting::CheckResult<void>(struct sol::protected_function_result)

**Comment by pull2play** [comment]
Ok, it seems I'm an idiot - **using the scrollbar** crashes the game. For some reason I always grab the scrollbar first, which lead me to believe that just opening the window caused a CTD. It doesn't. It's using the scrollbar that causes the crash.

**Comment by Gregory365** [comment]
Using the line scrollbar results in a crash
However, the line stop scrollbar does not

**Comment by Gregory365** [comment]
I'm not going to fix this issue until urban games fix their launcher. It is impossible to even load a game without this mod without it repeatedly crashing. Makes it very hard to debug

**Comment by Gregory365** [comment]
I will reopen when this issue become present in main game rather than testing/beta version. For now this mod is not supported for the beta
