### ISSUE TITLE
Is it possible to load timetable from an external file?

### ISSUE THREAD

**Issue by ConstasJ** [Gregory365/TPF2-Timetables#69]
Hi. I'm a Transport Fever 2 player who has played the game for a long time. I use your mod to add timetables for my train lines, and you know, it is a hard work to design a timetable. So I want to try some external tools like programming and Excel to help me design the timetable.
However, when I finished the design, I have to manually import my timetable by my hand. It is really a cumbersome work, so I wonder if there is any way to make import automatically.
Is there anyway to load a line's timetable from external file, like JSON file, CSV file or XLS/XLSX file?

**Comment by Gregory365** [comment]
The timetables are saved into the [sav.lua file](https://www.transportfever2.com/wiki/doku.php?id=gamemanual:gamefilelocations#game_file_locations) in the section named ["timetable_gui.lua"]. You could modify that (not when the game save is loaded though!)

The format of that section (for ArrDep format, where `_var_` denotes a variable and its type) is:
```
["timetable_gui.lua"] = {
    timetable = {
        [_intLineId_] = {
            frequency = _intIrrelevant_, -- Set to 1 or something. It will be updated as soon as you load the save.
            hasTimetable = _boolTimetableEnabled, -- Set to true.
            stations = {
                [_intStopNumber_] = { -- This is the position of the station in the line. So 2 would be the second stop in the line.
                    conditions = {
                        ArrDep = {
                            {_intArrivalMinute_, _intArrivalSecond_, _intDepartureMinute_, _intDepartureSecond_},
                            -- You can add as many of these timetable slots as you need
                        },
                        type = "ArrDep",
                    },
                    stationID = _intStationId_,
                    vehiclesWaiting = {}, -- Leave this empty. Make empty when editing the sav.lua.
                },
                -- You can add more stations here
            },
            -- You can add more lines here
        },
    },
},
```

Example sav.lua
```
["timetable_gui.lua"] = {
		timetable = {
			[7140] = {
				frequency = 209.41714867921,
				hasTimetable = true,
				stations = {
					{
						conditions = {
							ArrDep = {
								{ 0, 0, 1, 0, },
								{ 3, 0, 4, 0, },
								{ 6, 0, 7, 0, },
								{ 9, 0, 10, 0, },
								{ 12, 0, 13, 0, },
								{ 15, 0, 16, 0, },
								{ 18, 0, 19, 0, },
								{ 21, 0, 22, 0, },
								{ 24, 0, 25, 0, },
								{ 27, 0, 28, 0, },
								{ 30, 0, 31, 0, },
								{ 33, 0, 34, 0, },
								{ 36, 0, 37, 0, },
								{ 39, 0, 40, 0, },
								{ 42, 0, 43, 0, },
								{ 45, 0, 46, 0, },
								{ 48, 0, 49, 0, },
								{ 51, 0, 52, 0, },
								{ 54, 0, 55, 0, },
								{ 57, 0, 58, 0, },
							},
							type = "ArrDep",
						},
						stationID = 7135,
						vehiclesWaiting = {
							[7173] = { 15, 0, 16, 0, },
						},
					},
				},
			},
			[7141] = {
				frequency = 205.05653186655,
				hasTimetable = true,
				stations = {
					{
						conditions = {
							debounce = { 3, 0, },
							type = "debounce",
						},
						stationID = 7135,
					},
				},
			},
			[7142] = {
				frequency = 210.71785895288,
				hasTimetable = true,
				stations = {
					{
						conditions = {
							auto_debounce = { 1, 0, },
							type = "auto_debounce",
						},
						stationID = 7135,
					},
				},
			},
		},
	},
```


You'll need to obtain the line IDs and the station IDs that the game uses. 
You can get the IDs by copy/pasting the following command into the game console (Open with the ` key)

 For Line ID: (replace "Line 3" with the name of the line you want the ID of)
`api.engine.forEachEntityWithComponent(function(entity) if api.engine.getComponent(entity, api.type.ComponentType.NAME).name == "Line 3" then print(entity) end end,api.type.ComponentType.LINE)`

For station ID: (replace "Workington Branch" with the name of the station you want the ID of)
`api.engine.forEachEntityWithComponent(function(entity) if api.engine.getComponent(entity, api.type.ComponentType.NAME).name == "Workington Branch" then print(entity) end end,api.type.ComponentType.STATION)`

See the [API Reference](https://transportfever2.com/wiki/api/modules/api.engine.html) for a full list of the commands available.

**Comment by ConstasJ** [comment]
It is a way, but after I tried to do so, I find it is not friendly for program to complete the work, especially when I tried to sync the changes back to the sav.lua. Is there any other way that is more friendly to programs?

**Comment by Gregory365** [comment]
> It is a way, but after I tried to do so, I find it is not friendly for program to complete the work, especially when I tried to sync the changes back to the sav.lua. Is there any other way that is more friendly to programs?

What do you mean by friendly? The sav.lua is a text file that will be able to be read and written to by programs.

**Comment by Gregory365** [comment]
It's been a week and I haven't seem a reason why the provided solution wasn't acceptable, so I'm going to mark this as completed. Please open a new issue if the problem persists.
