### ISSUE TITLE
Using generate with multiple conditions crashes the game

### ISSUE THREAD

**Issue by Gregory365** [Gregory365/TPF2-Timetables#7]
### Repo steps

1. Create a line
2. Open the timetable for that line
3. Select a station, use Arr/Dep constraint
4. Add two or more arrival / departure slots
5. Select a generate frequency
6. Click generate

**Comment by Dinek05** [comment]
Now I know why my game crashed, this feature works only if there's only one slot before selecting generate, if there's two or more it crashed

**Comment by pull2play** [comment]
I don't know if this is somehow related to this or a separate issue entirely, but I've noticed (other than this crash) that auto-generation will often ignore the initial constraint and proceed to create correct intervals but with identical arrival and departure times (eg. arrive 12:00 depart 12:00, arrive 14:00, depart 14:00, and so on). This will happen intermittently and if the timetable is re-generated several times, it will eventually provide values with proper separation.

**Comment by Gregory365** [comment]
@pull2play Sorry, I'm unsure what you mean. Could you describe an example of what you did, the intended behavior, and how that differs from what happened?

**Comment by pull2play** [comment]
Attached images show what I'm trying to describe. In the first screenshot I've created the initial constraint and set the autogen parameters. As you can see, there's a difference between what I've input into the initial constraint and what is shown  on the timetable.
![20230124144531_1](https://user-images.githubusercontent.com/24781572/214315761-1185f5a3-f8ca-40d7-b342-b76e6464979b.jpg)

This is the result if I auto-generate the timetable with these parameters:

![20230124144554_1](https://user-images.githubusercontent.com/24781572/214315877-5a4327a2-61b6-46e1-a623-9c3941b2326d.jpg)

Now, if I then delete this manually and re-generate, it will create a correct timetable.

**Comment by Gregory365** [comment]
#10
