### ISSUE TITLE
Vehicles set to unbunch depart simultaneously from multiple platforms

### ISSUE THREAD

**Issue by darkrai-666** [Gregory365/TPF2-Timetables#71]
ive been trying to get my freight trains to not be back to back to eachother, but because they dont unbunch on the line, they arrive to the stabling yard in bunches, and currently, they all leave at the next timeslot. so the idea would be, to have a per station setting, that forces only 1 train to use a timeslot, with any remaining waiting on the next available slot(s)

**Comment by Gregory365** [comment]
If I am understanding you correctly. This feature is already implemented and tested. Only one vehicle can leave per timeslot.

**Comment by darkrai-666** [comment]
i just tested it on a seperate map, with just the sandbox and timetable 1.3 mods enabled, and instead of a single loco departing every minute, all locos currently in the station depart at the same time, ive recorded the test, maybe i am doing something wrong, but it would seem to me that it something isnt working quite right https://youtu.be/PGP5pxV6E68

**Comment by Gregory365** [comment]
I am testing the same thing on a map they departed sequentially. Can you share the sav.lua for that map?

**Comment by darkrai-666** [comment]
sure, this should be the file
https://pastebin.com/qPHcWdJp

**Comment by Gregory365** [comment]
Ok, thanks for the report. 
Arrival/Departure gives vehicles the next _available_ timeslot correctly.
Unbunch gives vehicles the next timeslot regardless of whether it is available, which is incorrect behaviour.

**Comment by darkrai-666** [comment]
using the version linked seems to have fixed this issue, thank you
