### ISSUE TITLE
All previous timetables are gone after the recent update

### ISSUE THREAD

**Issue by Dustin-Jiang** [Gregory365/TPF2-Timetables#76]
You can also found discussions at Workshop, eg, https://steamcommunity.com/workshop/filedetails/discussion/2918585390/4634861354807750974/

**Comment by Gregory365** [comment]
Thanks for the report. I have reverted timetables back to the previous version.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dustin Jiang ***@***.***>
Sent: Wednesday, November 13, 2024 4:20:49 PM
To: Gregory365/TPF2-Timetables ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Gregory365/TPF2-Timetables] All previous timetables are gone after the recent update (Issue #76)


You can also found discussions at Workshop, eg, https://steamcommunity.com/workshop/filedetails/discussion/2918585390/4634861354807750974/
